services:
  firm-deputy-hub:
    build:
      target: dev
    ports:
      - "2345:2345"
    volumes:
      - ./.air.toml:/app/.air.toml
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./internal:/app/internal
      - ./shared:/app/shared
      - ./main_test.go:/app/main_test.go
      - ./main.go:/app/main.go
      - ./web/static:/app/web/static
      - ./web/template:/app/web/template

  yarn:
    command: watch

  json-server:
    build:
      dockerfile: docker/json-server/Dockerfile
    volumes:
      - ./json-server/config:/app/config
    ports:
      - "3000:3000"
