version: "3.6"

services:
  firm-deputy-hub:
    build:
      context: ..
      dockerfile: ./docker/sirius-firm-deputy-hub/Dockerfile
    ports: ["8887:1234"]
    environment:
      SIRIUS_URL: http://docker.for.mac.localhost:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080
      PRO_HUB_HOST: http://localhost:8888
      PREFIX: /supervision/deputies/firm
