version: "3.6"

services:
  firm-deputy-hub:
    build:
      context: ..
      dockerfile: ./docker/sirius-firm-deputy-hub/Dockerfile
      target: dev
    ports:
      - "2345:2345"
      - "8888:1234"
    volumes:
      - ..:/app:rw,delegated
    environment:
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080
      PREFIX: /supervision/deputies/firm

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - "3000:3000"
