version: "3.6"

services:
  firm-deputy-hub:
    build:
      context: ..
      dockerfile: ./docker/sirius-firm-deputy-hub/Dockerfile
    ports: ["8888:8888"]
    environment:
      PORT: 8888
      SIRIUS_URL: http://json-server:3000
      PREFIX: /supervision/deputies/firm

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - "3000:3000"

  puppeteer:
    build: ./puppeteer
    depends_on:
      - firm-deputy-hub
      - json-server
    environment:
      - LHCI_BUILD_CONTEXT__CURRENT_HASH=$GITHUB_SHA
      - LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG=ministryofjustice/opg-sirius-supervision-firm-deputy-hub
      - LHCI_GITHUB_APP_TOKEN

  cypress:
    build:
      context: ..
      dockerfile: ./docker/cypress/Dockerfile
    command: ["--headless", "-b", "chrome"]
    volumes:
      - ../cypress/screenshots:/root/cypress/screenshots:rw,delegated
      - ../cypress/logs:/root/cypress/logs:rw,delegated
    depends_on:
      - firm-deputy-hub
      - json-server
