version: "3.6"

services:
  firm-deputy-hub:
    build:
      context: ..
      dockerfile: ./docker/sirius-firm-deputy-hub/Dockerfile
    ports: ["8888:1234"]
    environment:
      PREFIX: /supervision/deputies/firm