version: "3.6"

services:
  firm-deputy-hub:
    build:
      target: dev
    ports:
      - "2345:2345"
      - "8887:1234"
    volumes:
      - .:/app:rw,delegated
      - ./json-server/config:/app/config

  yarn:
    command: watch

  json-server:
    build:
      dockerfile: docker/json-server/Dockerfile
    ports:
      - "3000:3000"
